services:
    gamma.fixtures.booster.comman:
        class: Gamma\FixturesBoostBundle\Command\FixturesBoostCommand
        arguments: [@gamma.fixtures.database.handler, @gamma.fixtures.fixtures.handler]
        tags:
            -  { name: console.command }

    gamma.fixtures.fixtures.handler:
        class: Gamma\FixturesBoostBundle\Service\FixturesHandler
        arguments: [@doctrine.fixtures.load.command]

    gamma.fixtures.database.handler:
        class: Gamma\FixturesBoostBundle\Service\FixturesHandler
        arguments: [@doctrine.schema.drop.command, @doctrine.schema.create.command]

    doctrine.fixtures.load.command:
        class: Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand
        tags:
            -  { name: console.command }

    doctrine.schema.drop.command:
        class: Doctrine\Bundle\DoctrineBundle\Command\Proxy\DropSchemaDoctrineCommand
        tags:
            -  { name: console.command }

    doctrine.schema.create.command:
        class: Doctrine\Bundle\DoctrineBundle\Command\Proxy\CreateSchemaDoctrineCommand
        tags:
            -  { name: console.command }

